### ISSUE TITLE
Module: Moving of the player's meeple (token)

### ISSUE THREAD

**Issue by theRealBaccata** [Erasmus2016/frontend#3]
Hey Filip,

we are facing some problems with the movement of the player's meeple.

Right now, we are broadcasting from the backend after each movement of a player the new position of all players to all players.

Would you please implement the module to move the player's meeple from the old position to the new position?

The action is called _player-position_ and contains an array with all player's new position.

**Comment by FilipPyrek** [comment]
@theRealBaccata  And where is the problem here?

**Comment by FilipPyrek** [comment]
Or, what's the correlation between your problem and need for implementation?

**Comment by theRealBaccata** [comment]
This module is not implemented yet.

**Comment by FilipPyrek** [comment]
Yeah, I understood, but you have talked about some backend problem, so what is that problem?

> we are facing some problems with the movement of the player's meeple.

**Comment by theRealBaccata** [comment]
What's the problem at the backend regarding this frontend issue?

If you need some more information from the backend please let me know.

**Comment by FilipPyrek** [comment]
You said 

> we are facing some problems with the movement of the player's meeple.

so I have assumed that by *we* you mean backend, because you work on backend...

Probably there was some misunderstanding from my side.

**Comment by theRealBaccata** [comment]
Oh my bad.

No on the backend everything should work, the frontend part isn't done yet. That's the reason I opened this issue.

**Comment by FilipPyrek** [comment]
I see that I get from you in *player-position* the *id* of the fields the players are standing on. But I don't get information about the players - the colors.
Maby the key in the *player-position* object can be *color* instead of *player's id* and value will be the *id* of the field.

**Comment by theRealBaccata** [comment]
@FilipPyrek 
Please take a look at this commit:
https://github.com/Erasmus2016/backend/commit/bdb0e1268656aff17f0f884ee8db0165a580f2be

The backend will still send you all the players positions but in addition, the backend will send you also the players color.

**Comment by FilipPyrek** [comment]
It still doesn't work. 
When I changed 
```javascript
const positions = [];
```
to
```javascript
const positions = {};
```
it started working.

**Comment by FilipPyrek** [comment]
And we need you to send us the *player-position* event when you send us the *map* event. Because We don't know what color did the second player picked until the first *player-position* event.

**Comment by FilipPyrek** [comment]
@theRealBaccata I don't remember, is it done or not?

> And we need you to send us the player-position event when you send us the map event. Because We don't know what color did the second player picked until the first player-position event.

**Comment by theRealBaccata** [comment]
@FilipPyrek: Good question, I'll have a look at it and update you tomorrow.

**Comment by theRealBaccata** [comment]
@FilipPyrek :

1. This weakly typed array hotchpotch issue has been fixed.
2. We're sending the player-position event right after the map event to all players. Please have a look at https://github.com/Erasmus2016/backend/commit/feba52c402f2b8ca29089c95a61fa8197b12a81f

**Comment by FilipPyrek** [comment]
@theRealBaccata Great, it works. :+1:

**Comment by theRealBaccata** [comment]
@FilipPyrek:

Are there any backend issues or missing features left right now?

We would like to start working on the frontend/backend communication next week and trying to manage getting our backend functionality fully tested. We're sure there are any bugs our issues left, but we're unfit to detect them without testing.

We also believe we have to make some changes on the game logic and/or rules, depending on the game experience, e.g. making the map smaller.

**Comment by FilipPyrek** [comment]
@theRealBaccata Take a look at #2, maybe it's related to https://github.com/Erasmus2016/backend/issues/13.

**Comment by FilipPyrek** [comment]
I think we can close this. It was done in 64817ecb6ca34a185bec16021ab0271cc2bcb032. Now it just needs some styling (#6)
