### ISSUE TITLE
Issue: Proper handling of the login screen

### ISSUE THREAD

**Issue by theRealBaccata** [Erasmus2016/frontend#4]
Hey Filip,

could you please work on this issue:

The login screen is currently shown at the moment a new user browses to our website.

It would be better, if this login screen is only then available after the _login_ action was send from the backend.

**Comment by FilipPyrek** [comment]
ok

**Comment by theRealBaccata** [comment]
We would like to change this behavior in order to make sure every user will get only the player colors which are still available.

So first get the information from the backend and then create the welcome screen with only the remaining colors selectable.

**Comment by FilipPyrek** [comment]
It's done in *v2*. Now it just needs some styling.
